// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PensionatoApp.Data;

#nullable disable

namespace PI3_App.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PensionatoApp.Models.Hospede", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("ContatoEmergenciaNome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContatoEmergenciaTelefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Hospedes");
                });

            modelBuilder.Entity("PensionatoApp.Models.Notificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Lida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PagamentoId")
                        .HasColumnType("int");

                    b.Property<int?>("ReservaId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PagamentoId");

                    b.HasIndex("ReservaId");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("PensionatoApp.Models.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("FormaPagamento")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReservaId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("ValorPago")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ReservaId");

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("PensionatoApp.Models.RegistroLimpeza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataLimpeza")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsavelLimpeza")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SuiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SuiteId");

                    b.ToTable("RegistrosLimpeza");
                });

            modelBuilder.Entity("PensionatoApp.Models.RegistroManutencao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsavelManutencao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SuiteId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SuiteId");

                    b.ToTable("RegistrosManutencao");
                });

            modelBuilder.Entity("PensionatoApp.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataSaida")
                        .HasColumnType("datetime2");

                    b.Property<int>("HospedeId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Origem")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoArCondicionado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PrecoGaragem")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SuiteId")
                        .HasColumnType("int");

                    b.Property<bool>("TemArCondicionado")
                        .HasColumnType("bit");

                    b.Property<bool>("TemGaragem")
                        .HasColumnType("bit");

                    b.Property<decimal>("ValorAdiantado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorCaucao")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorMensalTotal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("HospedeId");

                    b.HasIndex("SuiteId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("PensionatoApp.Models.Suite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ArCondicionado")
                        .HasColumnType("bit");

                    b.Property<bool>("ArmarioEmbutido")
                        .HasColumnType("bit");

                    b.Property<bool>("Geladeira")
                        .HasColumnType("bit");

                    b.Property<bool>("MesaEstudos")
                        .HasColumnType("bit");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecoArCondicionado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PrecoMensal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("QuadrosDecorativos")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipoCama")
                        .HasColumnType("int");

                    b.Property<bool>("Ventilador")
                        .HasColumnType("bit");

                    b.Property<bool>("WiFi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Suites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArCondicionado = false,
                            ArmarioEmbutido = true,
                            Geladeira = true,
                            MesaEstudos = true,
                            Numero = 1,
                            PrecoArCondicionado = 150.00m,
                            PrecoMensal = 1700.00m,
                            QuadrosDecorativos = true,
                            Status = 0,
                            TipoCama = 1,
                            Ventilador = true,
                            WiFi = true
                        },
                        new
                        {
                            Id = 2,
                            ArCondicionado = false,
                            ArmarioEmbutido = true,
                            Geladeira = true,
                            MesaEstudos = true,
                            Numero = 2,
                            PrecoArCondicionado = 150.00m,
                            PrecoMensal = 1600.00m,
                            QuadrosDecorativos = true,
                            Status = 0,
                            TipoCama = 0,
                            Ventilador = true,
                            WiFi = true
                        },
                        new
                        {
                            Id = 3,
                            ArCondicionado = false,
                            ArmarioEmbutido = true,
                            Geladeira = true,
                            MesaEstudos = true,
                            Numero = 3,
                            PrecoArCondicionado = 150.00m,
                            PrecoMensal = 1750.00m,
                            QuadrosDecorativos = true,
                            Status = 0,
                            TipoCama = 1,
                            Ventilador = true,
                            WiFi = true
                        },
                        new
                        {
                            Id = 4,
                            ArCondicionado = false,
                            ArmarioEmbutido = true,
                            Geladeira = true,
                            MesaEstudos = true,
                            Numero = 4,
                            PrecoArCondicionado = 150.00m,
                            PrecoMensal = 1750.00m,
                            QuadrosDecorativos = true,
                            Status = 0,
                            TipoCama = 1,
                            Ventilador = true,
                            WiFi = true
                        },
                        new
                        {
                            Id = 5,
                            ArCondicionado = false,
                            ArmarioEmbutido = true,
                            Geladeira = true,
                            MesaEstudos = true,
                            Numero = 5,
                            PrecoArCondicionado = 150.00m,
                            PrecoMensal = 1900.00m,
                            QuadrosDecorativos = true,
                            Status = 0,
                            TipoCama = 1,
                            Ventilador = true,
                            WiFi = true
                        },
                        new
                        {
                            Id = 6,
                            ArCondicionado = false,
                            ArmarioEmbutido = true,
                            Geladeira = true,
                            MesaEstudos = true,
                            Numero = 6,
                            PrecoArCondicionado = 150.00m,
                            PrecoMensal = 1700.00m,
                            QuadrosDecorativos = true,
                            Status = 0,
                            TipoCama = 1,
                            Ventilador = true,
                            WiFi = true
                        },
                        new
                        {
                            Id = 7,
                            ArCondicionado = false,
                            ArmarioEmbutido = true,
                            Geladeira = true,
                            MesaEstudos = true,
                            Numero = 7,
                            PrecoArCondicionado = 150.00m,
                            PrecoMensal = 1700.00m,
                            QuadrosDecorativos = true,
                            Status = 0,
                            TipoCama = 1,
                            Ventilador = true,
                            WiFi = true
                        },
                        new
                        {
                            Id = 8,
                            ArCondicionado = false,
                            ArmarioEmbutido = true,
                            Geladeira = true,
                            MesaEstudos = true,
                            Numero = 8,
                            PrecoArCondicionado = 150.00m,
                            PrecoMensal = 1600.00m,
                            QuadrosDecorativos = true,
                            Status = 0,
                            TipoCama = 0,
                            Ventilador = true,
                            WiFi = true
                        },
                        new
                        {
                            Id = 9,
                            ArCondicionado = false,
                            ArmarioEmbutido = true,
                            Geladeira = true,
                            MesaEstudos = true,
                            Numero = 9,
                            PrecoArCondicionado = 150.00m,
                            PrecoMensal = 1700.00m,
                            QuadrosDecorativos = true,
                            Status = 0,
                            TipoCama = 1,
                            Ventilador = true,
                            WiFi = true
                        },
                        new
                        {
                            Id = 10,
                            ArCondicionado = false,
                            ArmarioEmbutido = true,
                            Geladeira = true,
                            MesaEstudos = true,
                            Numero = 10,
                            PrecoArCondicionado = 150.00m,
                            PrecoMensal = 1600.00m,
                            QuadrosDecorativos = true,
                            Status = 0,
                            TipoCama = 0,
                            Ventilador = true,
                            WiFi = true
                        },
                        new
                        {
                            Id = 11,
                            ArCondicionado = false,
                            ArmarioEmbutido = true,
                            Geladeira = true,
                            MesaEstudos = true,
                            Numero = 11,
                            PrecoArCondicionado = 150.00m,
                            PrecoMensal = 1700.00m,
                            QuadrosDecorativos = true,
                            Status = 0,
                            TipoCama = 1,
                            Ventilador = true,
                            WiFi = true
                        });
                });

            modelBuilder.Entity("PensionatoApp.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NomeCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PensionatoApp.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PensionatoApp.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PensionatoApp.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PensionatoApp.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PensionatoApp.Models.Notificacao", b =>
                {
                    b.HasOne("PensionatoApp.Models.Pagamento", "Pagamento")
                        .WithMany()
                        .HasForeignKey("PagamentoId");

                    b.HasOne("PensionatoApp.Models.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("ReservaId");

                    b.Navigation("Pagamento");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("PensionatoApp.Models.Pagamento", b =>
                {
                    b.HasOne("PensionatoApp.Models.Reserva", "Reserva")
                        .WithMany("Pagamentos")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("PensionatoApp.Models.RegistroLimpeza", b =>
                {
                    b.HasOne("PensionatoApp.Models.Suite", "Suite")
                        .WithMany("RegistrosLimpeza")
                        .HasForeignKey("SuiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Suite");
                });

            modelBuilder.Entity("PensionatoApp.Models.RegistroManutencao", b =>
                {
                    b.HasOne("PensionatoApp.Models.Suite", "Suite")
                        .WithMany("RegistrosManutencao")
                        .HasForeignKey("SuiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Suite");
                });

            modelBuilder.Entity("PensionatoApp.Models.Reserva", b =>
                {
                    b.HasOne("PensionatoApp.Models.Hospede", "Hospede")
                        .WithMany("Reservas")
                        .HasForeignKey("HospedeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PensionatoApp.Models.Suite", "Suite")
                        .WithMany("Reservas")
                        .HasForeignKey("SuiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hospede");

                    b.Navigation("Suite");
                });

            modelBuilder.Entity("PensionatoApp.Models.Hospede", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("PensionatoApp.Models.Reserva", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("PensionatoApp.Models.Suite", b =>
                {
                    b.Navigation("RegistrosLimpeza");

                    b.Navigation("RegistrosManutencao");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
